package com.btl.quanlythuvien.Enity;

public class Z36 {
    private String Z36_REC_KEY;
    private String Z36_ID;
    private String Z36_NUMBER;
    private String Z36_MATERIAL;
    private String Z36_SUB_LIBRARY;
    private String Z36_STATUS;
    private String Z36_LOAN_DATE;
    private String Z36_LOAN_HOUR;
    private String Z36_EFFECTIVE_DUE_DATE;
    private String Z36_DUE_DATE;
    private String Z36_DUE_HOUR;
    private String Z36_RETURNED_DATE;
    private String Z36_RETURNED_HOUR;
    private String Z36_ITEM_STATUS;
    private String Z36_BOR_STATUS;
    private String Z36_LETTER_NUMBER;
    private String Z36_LETTER_DATE;
    private String Z36_NO_RENEWAL;
    private String Z36_NOTE_1;
    private String Z36_NOTE_2;
    private String Z36_LOAN_CATALOGER_NAME;
    private String Z36_LOAN_CATALOGER_IP;
    private String Z36_RETURN_CATALOGER_NAME;
    private String Z36_RETURN_CATALOGER_IP;
    private String Z36_RENEW_CATALOGER_NAME;
    private String Z36_RENEW_CATALOGER_IP;
    private String Z36_RENEW_MODE;
    private String Z36_BOR_TYPE;
    private String Z36_NOTE_ALPHA;
    private String Z36_RECALL_DATE;
    private String Z36_RECALL_DUE_DATE;
    private String Z36_LAST_RENEW_DATE;
    private String Z36_ORIGINAL_DUE_DATE;
    private String Z36_PROCESS_STATUS;
    private String Z36_LOAN_TYPE;
    private String Z36_RECALL_TYPE;
    private String Z36_RETURN_LOCATION;
    private String Z36_RETURN_SUB_LOCATION;
    private String Z36_SOURCE;
    private String Z36_DELIVERY_TIME;
    private String Z36_TAIL_TIME;
    private String Z36_UPD_TIME_STAMP;
}
