/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.btl.quanlythuvien.gui.bib;

import com.btl.quanlythuvien.Business.BusZ00;
import com.btl.quanlythuvien.Enity.Z00;
import com.btl.quanlythuvien.controler.Marc2;
import com.btl.quanlythuvien.controler.MarcBean2;
import com.btl.quanlythuvien.model.DBConnection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

/**
 * @author Admin
 */
public class ViewItem extends javax.swing.JFrame {
    private String table, value;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA_bib;
    private javax.swing.JTable jtable_item;
    private Connection connection;
    private DBConnection conn;
    private PreparedStatement statement;
    private Vector vTitle;
    private JTable jTable;
    private Vector vData;
    private JScrollPane tableResult;
    private List<Z00> z00s;

    /**
     * Creates new form ViewItem
     */
    public ViewItem(String table, String value) {
        this.table = table;
        this.value = value;
        z00s = new ArrayList<>();
        conn = new DBConnection();
        initComponents();
        getData();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public JScrollPane makeTable(String sql) {
        if (jScrollPane1 != null) {
            remove(jScrollPane1);
        }
        vTitle = new Vector<String>();
        vData = new Vector<>();
        try {
            vTitle.clear();
            vData.clear();
            connection = new DBConnection().getConnection();
            statement = connection.prepareStatement(sql);
            ResultSet rst = statement.executeQuery();
            ResultSetMetaData metaData = statement.getMetaData();
            int column = metaData.getColumnCount();
            for (int i = 1; i <= column; i++) {
                vTitle.add(metaData.getColumnLabel(i));
            }

            while (rst.next()) {
                Vector<String> row = new Vector<String>(column);
                for (int i = 1; i <= column; i++)
                    row.add(rst.getString(i));
                vData.add(row);
            }
            rst.close();
            statement.close();
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel defaultTableModel = new DefaultTableModel(vData, vTitle);
        jtable_item = new JTable(defaultTableModel);
        jScrollPane1 = new JScrollPane(jtable_item);
        jtable_item.setShowGrid(true);
        jtable_item.setFillsViewportHeight(true);
        return jScrollPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_bib = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_item = new javax.swing.JTable();

        jTA_bib.setColumns(20);
        jTA_bib.setRows(5);
        jScrollPane2.setViewportView(jTA_bib);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        jtable_item.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jtable_item);
        String sql = "Select Z30_BARCODE AS 'Barcode'," +
                "Z30_REC_KEY AS 'Mã sách'," +
                "Z30_SUB_LIBRARY AS 'Mã thư viện'," +
                "Z30_MATERIAL AS 'Loại tài liệu'," +
                "Z30_ITEM_STATUS AS 'Trạng thái'," +
                "Z30_COLLECTION AS 'Bộ sưu tập'," +
                "Z30_PRICE AS 'Giá' From z30 where Z30_REC_KEY=" + value;
        makeTable(sql);
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getData() {
        String data = "";
        BusZ00 busZ00 = new BusZ00(conn);
        z00s = busZ00.getOneTable(value);
        data = z00s.get(0).getZ00_DATA();

        MarcBean2 marcBean2 = Marc2.marcBeans(value, data);
        System.out.println(marcBean2);
        jTA_bib.setText(marcBean2.toString());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables
}
